#!/bin/bash

# This script is used to modify the opf file, the opf file is generated by using docbook-xml/epub/docbook-opf.xsl in collectiondbk2mobi.py.
# Here the script's usage is to:
# 1. Specify the book cover which located in the unzipped collection, under the name of "cover.png";
# 2. Add a "Table of Content" entry in Kindle's "Go-To" menue;
# NOTICE: the opf file is stored in the unzipped collection, under the name of "content.opf". This is specified in the docbook-opf.xsl

#1st param is the book content: html file;
#2nd param is the name of the unzipped collection which contains the book cover: cover.png and opf file: content.opf

HTML_FILE=$1
WORKING_DIR=$2

EXIT_STATUS=0

cover_info="<x-metadata><EmbeddedCover>cover.png</EmbeddedCover></x-metadata></metadata>"
toc_info='<manifest><item id="item1" media-type="text/x-oeb1-document" href="'${HTML_FILE}'"></item></manifest><spine><itemref idref="item1"/></spine><guide><reference href="'${HTML_FILE}'#toc" type="toc" title="Table of Contents"/></guide></package>'

if [ -s ${WORKING_DIR}/content.opf ]; then
  sed -i "s,<\/metadata>,${cover_info}," ${WORKING_DIR}/content.opf
  sed -i "s,<\/package>,${toc_info},"  ${WORKING_DIR}/content.opf
else
  echo "ERROR: The second argument does not point to a directory containing a 'content.opf' file" 1>&2
  $EXIT_STATUS=1
fi
exit $EXIT_STATUS
